package utils

const (
	// ASSISTANT_VERSION ...
	ASSISTANT_VERSION = "0.0.1"

	API_ASSISTANT_VERSION = "V1.0"
	PULL_TASK_URI         = "/task/pull"
	REPLY_TASK_URI        = "/task/reply"
	POST_HEARTBEAT_URI    = "/heartbeat"

	// SERVICE for IAM signer
	SERVICE = "CES"

	PULL_TASK_INTERVAL_IN_SECOND      = 10
	REPLY_TASK_INTERVAL_IN_SECOND     = 5
	SEND_HEARTBEAT_INTERVAL_IN_SECOND = 60
)
